### ISSUE TITLE
React Can't resolve 'react/jsx-runtime'

### ISSUE THREAD

**Issue by MadikMayCry** [fingerprintjs/fingerprintjs-pro-react#90] opened 2023-01-19 11:48 UTC
Module not found: Error: Can't resolve 'react/jsx-runtime' 

react: 17.02
typescript

alias: {
'react/jsx-runtime': 'react/jsx-runtime'
}

**Comment by ilfa** [comment] 2023-01-23 08:35
Hi @MadikMayCry!

I tried to use the library with 17th react and everything works well.

I installed it with create-react-app an used [this instruction](https://github.com/facebook/create-react-app/issues/12269#issuecomment-1154101796) to revert react version from 18 to 17.

Can you provide more information about your problem?

**Comment by MadikMayCry** [comment] 2023-01-23 08:40
we are using custom ssr & webpack
![image](https://user-images.githubusercontent.com/34336498/213996780-2479a2aa-a31a-45c4-af88-1aeefeeb0563.png)
![image](https://user-images.githubusercontent.com/34336498/213996907-9b640c92-02fb-4a9f-810f-0ab0c1ef29d9.png)

**Comment by ilfa** [comment] 2023-01-23 08:55
Did you try to use this alias?

```
alias: {
'react/jsx-runtime': 'react'
}
```

**Comment by JuroUhlar** [comment] 2024-03-15 17:55
I am going to close this as the necessary debugging information hasn't been provided in over a year and the library now officially requires React 18 or higher. 

Let me know if the problem is still relevant and I can reopen the issue, cheers.

**Closed by JuroUhlar** 2024-03-15 17:55 UTC
